from .createpost import TestCreatePost
from .deletepost import TestDeletePost
from .editpost import TestEditPost
from .login import TestLogin
from .logout import TestLogout
from .post import TestPostDetail
from .posts import TestPosts
from .createtag import TestCreateTag
from .deletetag import TestDeleteTag